name: observability

networks:
  obs-net:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data:
  loki-data:

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}

    restart: unless-stopped

    hostname: grafana

    env_file:
      - ./.env

    ports:
      - "${GRAFANA_PORT}:3000"

    networks:
      - obs-net

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

    security_opt:
      - no-new-privileges:true

    logging:
    # Prevent unlimited Docker log growth.
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5

    mem_limit: 1g

    # cpus: 1